---
- hosts: localhost
  tasks:
 
  - name: Gather AWS S3 Facts 
    aws_s3_bucket_facts:
      aws_access_key: "{{lookup('env','AWS_ACCESS_KEY_ID')}}"
      aws_secret_key: "{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
    register: aws_s3_bucket_facts

  - name: Debug
    debug:
      msg: "{{ aws_s3_bucket_facts }}"
