---
- hosts: localhost
  tasks:
 
  - name: Gather Elastic IP Facts
    ec2_eip_facts:
      aws_access_key: "{{lookup('env','AWS_ACCESS_KEY_ID')}}"
      aws_secret_key: "{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
    register: ec2_eip_facts

  - name: Display Return Data
    debug:
      msg: "{{ ec2_eip_facts }}"
