---
- hosts: localhost
  tasks:
 
  - name: Gather EC2 Facts 
    ec2_instance_facts:
      aws_access_key: "{{lookup('env','AWS_ACCESS_KEY_ID')}}"
      aws_secret_key: "{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
    register: ec2_facts

  - name: Debug
    debug:
      msg: "{{ ec2_facts }}"
