#!/bin/bash

#Check Point Automation Training 

#Login
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_gw_user'","password":"'$cp_gw_pass'"}' $cp_gw_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64


#set routes
echo '[+] Set Route'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"address": "4.2.2.4","mask-length":32,"nexthop-address":"192.168.1.1","state": true}' \
$cp_gw_url/set-static-route | ./jq-linux64

