#!/bin/bash

#Check Point Automation Training 

#Login
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_gw_user'","password":"'$cp_gw_pass'"}' $cp_gw_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64


#set ntp 
echo '[+] Set NTP Server'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"host":"0.pool.ntp.org","version":"1"}' \
$cp_gw_url/set-ntp/primary | ./jq-linux64

