---
- hosts: "{{lookup('env','cp_gw_ip')}}" 
  gather_facts: no
  tasks:

  - name: "Configure DNS and NTP"
    command: "{{ item }}"
    ignore_errors: yes
    with_items:
    - clish -c "lock database override"
    - clish -c "set dns primary 1.1.1.1"
    - clish -c "set dns secondary 8.8.8.8"
    - clish -c "set ntp server primary 0.pool.ntp.org version 1"
    - clish -c "set ntp server primary 1.pool.ntp.org version 1"
    - clish -c "save config"

- hosts: "{{lookup('env','cp_mgmt_ip')}}"
  gather_facts: no
  tasks:

  - name: "Configure DNS and NTP"
    command: "{{ item }}"
    ignore_errors: yes
    with_items:
    - clish -c "lock database override"
    - clish -c "set dns primary 1.1.1.1"
    - clish -c "set dns secondary 8.8.8.8"
    - clish -c "set ntp server primary 0.pool.ntp.org version 1"
    - clish -c "set ntp server primary 1.pool.ntp.org version 1"
    - clish -c "save config"

