#!/bin/bash

#Check Point Automation Training 

#Login and retrieve the session_id
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_mgmt_user'","password":"'$cp_mgmt_pass'","session-name":"Bash Add Threat IOC"}' $cp_mgmt_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64

#Add Threat IOC
echo ''
echo '[+] Add Threat IOC'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"name":"MaliciousHost","observables":[{"name":"MaliciousHost","ip-address":"4.2.2.4","confidence":"high","product":"AV","severity":"high","comments":"Added From IOC API"}]}' \
$cp_mgmt_url/add-threat-indicator | ./jq-linux64 

#publish
echo ''
echo '[+] Publish'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{}' \
$cp_mgmt_url/publish | ./jq-linux64

#logout
echo ''
echo '[+] Logout'
curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -H "X-chkp-sid: $SID" -X POST -d '{}' $cp_mgmt_url/logout | ./jq-linux64
