#!/bin/bash

#Check Point Automation Training 

#Login and retrieve the session_id
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_mgmt_user'","password":"'$cp_mgmt_pass'","session-name":"Bash Show Threat IOC"}' $cp_mgmt_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64

#Show Threat IOC (Note: This call is from API Server versions 1.2 or newer)
echo ''
echo '[+] Show Threat IOCs'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"details-level":"full"}' \
$cp_mgmt_url/show-threat-indicators | ./jq-linux64 

#logout
echo ''
echo '[+] Logout'
curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -H "X-chkp-sid: $SID" -X POST -d '{}' $cp_mgmt_url/logout | ./jq-linux64
