#!/bin/bash

#Check Point Automation Training 

#Login and retrieve the session_id
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_mgmt_user'","password":"'$cp_mgmt_pass'","session-name":"Bash Run Script"}' $cp_mgmt_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64

#RunScript
echo ''
echo '[+] Run Script'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"script-name":"FW SAM Block","script":"fw sam -v -s localhost -f All -t 600 -l long_noalert -j src 12.11.11.11","targets":"HomeMgr"}' \
$cp_mgmt_url/run-script | ./jq-linux64 

#logout
echo ''
echo '[+] Logout'
curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -H "X-chkp-sid: $SID" -X POST -d '{}' $cp_mgmt_url/logout | ./jq-linux64
