#!/bin/bash

#Check Point Automation Training

#AZ VM Delete
echo '[+] AZ VM Delete'
az vm delete --resource-group AutomationTraining --name UbuntuVM --yes | ./jq-linux64

#Delete Resource Group
echo '[+] AZ Group Delete'
az group delete -n AutomationTraining --no-wait --yes | ./jq-linux64




