#!/bin/bash

#Check Point Automation Training 

#Login and retrieve the session_id
echo '[+] Login'
LOGIN=`curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -X POST -d '{"user":"'$cp_mgmt_user'","password":"'$cp_mgmt_pass'","session-name":"Bash Add Host"}' $cp_mgmt_url/login`
SID=`echo $LOGIN | ./jq-linux64 '.sid' | sed s/\"//g`
echo $LOGIN | ./jq-linux64

#Get UID of Object
echo ''
echo '[+] Find Object UID'
QUERY=`curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"name":"FW3200"}' \
$cp_mgmt_url/show-simple-gateway` 
CP_UID=`echo $QUERY | ./jq-linux64 '.uid' | sed s/\"//g`
echo $CP_UID 

#Show Generic Object
echo ''
echo '[+] Show Generic Object'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"uid":"'$CP_UID'","details-level":"full"}' \
$cp_mgmt_url/show-generic-object | ./jq-linux64 '.interfaces' 

#Set Generic Object
echo ''
echo '[+] Set Generic Object'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{"uid":"'$CP_UID'","interfaces.1.comments":"MyInterfaceComment!"}' \
$cp_mgmt_url/set-generic-object | ./jq-linux64 

#publish
echo ''
echo '[+] Publish'
curl -s -k \
-H "Content-Type: application/json" \
-H "Accept: bla" \
-H "X-chkp-sid: $SID" \
-X POST -d '{}' \
$cp_mgmt_url/publish | ./jq-linux64

#logout
echo ''
echo '[+] Logout'
curl -s -k -H "Content-Type: application/json" -H "Accept: bla" -H "X-chkp-sid: $SID" -X POST -d '{}' $cp_mgmt_url/logout | ./jq-linux64
